helm-extra-args: --timeout 600
check-version-increment: false 
debug: true
chart-repos: 
  - bitnami=https://charts.bitnami.com/bitnami
  - kubernetes=https://kubernetes-charts.storage.googleapis.com/
target-branch: main
