apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: bookstack
    meta.helm.sh/release-namespace: bookstack
  generation: 1
  labels:
    app.kubernetes.io/instance: bookstack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bookstack
    app.kubernetes.io/version: 22.11.0
    helm.sh/chart: bookstack-0.1.1
  name: bookstack
  namespace: bookstack
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: bookstack
      app.kubernetes.io/name: bookstack
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: bookstack
        app.kubernetes.io/name: bookstack
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: bookstack.bookstack-mariadb.svc.cluster.local
        - name: DB_DATABASE
          value: bookstack
        - name: DB_USER
          value: bookstack
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: mariadb-password
              name: bookstack-mariadb
        - name: APP_URL
          value: https://bookstack.dlwhitehurst.com
        image: solidnerd/bookstack:22.11.0
        imagePullPolicy: Always
        name: bookstack
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/bookstack/public/uploads
          name: uploads
        - mountPath: /var/www/bookstack/storage/uploads
          name: storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bookstack
      serviceAccountName: bookstack
      terminationGracePeriodSeconds: 30
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: bookstack-uploads
      - name: storage
        persistentVolumeClaim:
          claimName: bookstack-storage
