{{- if .Values.rbac.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "bookstack.fullname" . }}
  labels:
    app: {{ include "bookstack.name" . }}
    chart: {{ include "bookstack.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
{{- if .Values.podSecurityPolicy.enabled }}
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [{{ include "bookstack.fullname" . }}]
{{- end }}
{{- end }}
