apiVersion: v2
appVersion: 1.33.1
dependencies:
  - name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 11.4.2
description: Extremely powerful, scalable software and a feature-rich wiki implementation
  that uses PHP to process and display data stored in a database.
engine: gotpl
home: http://www.mediawiki.org/
icon: https://bitnami.com/assets/stacks/mediawiki/img/mediawiki-stack-220x234.png
keywords:
- mediawiki
- wiki
- http
- web
- application
- php
- abc
maintainers:
- email: containers@bitnami.com
  name: Bitnami
- name: dlwhitehurst
name: mediawiki
sources:
- https://github.com/bitnami/bitnami-docker-mediawiki
version: 9.0.1
